language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - g++
      - gfortran
      - valgrind
      - csh
      - g++-multilib
      - gcc-multilib

branches:
  only:
    - master

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # Add omnia channel
  - conda config --add channels http://conda.anaconda.org/${ORGNAME}
  # build the recipe
  - conda build devtools/conda-recipe
  # Install the package and test it
  - conda install --yes --quiet ${PACKAGENAME}-dev
  - conda install --yes --quiet nose nose-timer
  - nosetests ${PACKAGENAME} --nocapture --verbosity=2 --with-doctest --with-timer

  - source devtools/ci/ipythontests.sh

env:
  matrix:
    # Changes to CONDA_NPY needed for pymc binstar availability.
    - python=2.7  CONDA_PY=27  CONDA_NPY=19
    #- python=2.7  CONDA_PY=27  CONDA_NPY=16
    #- python=3.3  CONDA_PY=33  CONDA_NPY=17
    #- python=3.4  CONDA_PY=34  CONDA_NPY=18

  global:
    - ORGNAME: "choderalab"
    - PACKAGENAME: "assaytools"
    # TODO: add encrypted AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to push documentation to S3
    # binstar
    - secure: "x/7fFUnTGXdQOiAduc8ONAiVOV63vgup1y4heemW/Z1fnhjAgNIjwIX0/9cJtV0HU7ayLXaBcMy6Bq72W49wIKZM6omvx6sazZ6ju0EUrp6GKQmZqio255cV2RA810uSTpNh2lIwkMPWfWfv2VmBzKsJyM4eKHrVdKsLUCGu7M4="

after_success:
  - echo "after_success"
  - ./devtools/travis-ci/after_success.sh
