language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export CC=gcc
  - export CXX=g++

script:
  - source deactivate
  - conda config --add channels https://conda.binstar.org/omnia
  - conda install --yes conda-build jinja2 binstar pip
  - conda build devtools/conda-recipe
  - source activate $python
  - conda install --yes $HOME/miniconda/conda-bld/linux-64/assaytools-dev-*
  - conda list -e
  # pydir=$(which python); $precmd $(dirname $pydir)/nosetests --exclude-dir=AssayTools/html --with-coverage --cover-erase -vv

env:
  matrix:
    - python=2.7  CONDA_PY=27  CONDA_NPY=16
    - python=3.3  CONDA_PY=33  CONDA_NPY=17
    - python=3.4  CONDA_PY=34  CONDA_NPY=18

  global:
    # TODO: add encrypted AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to push documentation to S3
    # TODO: add encrypted BINSTAR_TOKEN for push of dev package to binstar

after_success:
  - echo "after_success"
  - source devtools/ci/after_sucess.sh
