language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export CC=gcc
  - export CXX=g++

script:
  - source deactivate
  - conda config --add channels https://conda.binstar.org/omnia
  - conda install --yes conda-build jinja2 binstar pip
  - conda build devtools/conda-recipe
  - source activate $python
  - conda install --yes $HOME/miniconda/conda-bld/linux-64/assaytools-dev-*
  - conda list -e
  # pydir=$(which python); $precmd $(dirname $pydir)/nosetests --exclude-dir=AssayTools/html --with-coverage --cover-erase -vv

env:
  matrix:
    # Changes to CONDA_NPY needed for pymc binstar availability.
    - python=2.7  CONDA_PY=27  CONDA_NPY=19
    #- python=2.7  CONDA_PY=27  CONDA_NPY=16
    #- python=3.3  CONDA_PY=33  CONDA_NPY=17
    #- python=3.4  CONDA_PY=34  CONDA_NPY=18

  global:
    # TODO: add encrypted AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to push documentation to S3
    # binstar
    secure: "x/7fFUnTGXdQOiAduc8ONAiVOV63vgup1y4heemW/Z1fnhjAgNIjwIX0/9cJtV0HU7ayLXaBcMy6Bq72W49wIKZM6omvx6sazZ6ju0EUrp6GKQmZqio255cV2RA810uSTpNh2lIwkMPWfWfv2VmBzKsJyM4eKHrVdKsLUCGu7M4="

after_success:
  - echo "after_success"
  - source devtools/ci/after_sucess.sh
