package:
  name: assaytools-dev
  version: !!str 0.1.0

source:
  path: ../..

build:
  entry_points:
    - xml2png = assaytools.scripts.xml2png:entry_point

requirements:
  build:
    - setuptools
    - python
    - numpy
    - pint
    - pandas
    - scipy
    - pymc
    - matplotlib
    - seaborn
    - lxml
    - ipython
    - notebook

  run:
    - python
    - numpy
    - pint
    - pandas
    - scipy
    - pymc
    - matplotlib
    - seaborn
    - lxml
    - ipython
    - notebook

test:
  requires:
    - nose
    - scripttest
    - ipython
    - notebook
    - ipynbtest
  imports:
    - assaytools

about:
  home: http://assaytools.choderalab.org
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A library for the modeling and analysis of plate-based assays (development snapshot)
